inertialsense/inertial-sense-sdk

python/logInspector/CMakeLists.txt
This allows building the Pybind11 package without the internal folder structure.
=> Fix the Python build by using find_package for pybind11 & fixing the paths

CMakeLists.txt
This makes much easier integrating this project as a subdirectory on other cmake projects.
Just add the dependency:
<pre>
target_link_libraries( yourproject
PRIVATE
InertialSense::libinertialsense
Boost::date_time
)
</pre>
other changes using the target_xxxx cmake functions would be welcome, but this is the minimal change required
feel free to use a alias name, but it needs to be "namespaced"
=> add namespaced target name for the library

EVB-2/IS_EVB-2/src/control_law.cpp, EVB-2/IS_EVB-2/src/globals.c, src/data_sets.h
This converts all encoderTickToWheelRad constants to represent the rated encoder count without multiplying by 2.
=> Switch encoderTickToWheelRad to represent single channel encoder count

EVB-2/IS_EVB-2/src/communications.cpp, EVB-2/IS_EVB-2/src/drivers/d_quadEnc.c, EVB-2/IS_EVB-2/src/drivers/d_quadEnc.h, EVB-2/IS_EVB-2/src/wheel_encoder.cpp, src/ISComm.h, src/ISDataMappings.cpp, src/cltool.cpp, src/data_sets.h
- Ability to reverse wheel encoder direction on EVB2.
- CLTool now accepts a space between -c and part name so we can use tab completion.  Old method is still supported for compatibility.
=> Luna 1118 encoder direction config

python/pylib/pose.py
I added a few functions to pylib.pose that were defined elsewhere and left a couple of them (conversion between LLA and NED) commented out because:
1. We are not using them
2. I don't want to lose them because they provide more accurate conversion than LLA-NED functions currently defined in pylib.pose
=> Python cleanup

ExampleProjects/Ascii/ISAsciiExample.c, src/protocol_nmea.cpp, src/protocol_nmea.h
- Fixed issue were g_asciiPeriodPPIMU wasn't getting set properly when the ASCB enable broadcast message was used.
- Added correct number of commas to ASCB message in AsciiExampleProject.
=> Fixed pimu and ppimu ASCII broadcast issue

.gitignore, cltool/CMakeLists.txt, src/ISDataMappings.h, src/cltool.cpp, src/data_sets.h, src/luna_data_sets.h
We now include luna_data_sets.h in the inertial-sense-sdk.  It gets include automatically with Luna and we can use a INCLUDE_LUNA_DATA_SETS macro to enable it in the cltool and EvalTool (for Luna development / debug).
=> Move luna_data_sets.h into inertial-sense-sdk/src

ExampleProjects/Bootloader/ISBootloaderExample.c, ExampleProjects/Bootloader/README.md, cltool/VS_project/cltool.vcxproj.user, src/inertialSenseBootLoader.c
Previously, enabling the bootloader would only work for supported bootloader baudrates (921600, 230400, 115200, 2000000) but now works for all supported IS baudrates.
=> SN-453 Fixed bootloader non-standard baudrate issue

src/data_sets.h
Add method to disable communications serial port 2 (ser2) to prevent built-in test (BIT) failure when CAN transceiver is present.  Add protection/prevention for use of EvalTool and uINS firmware protocol versions don't match.
=> SN-446 add comm port disable to fix bit

ExampleProjects/Ascii/VS_Project/ISAsciiExample.vcxproj, ExampleProjects/Bootloader/VS_Project/ISBootloaderExample.vcxproj, ExampleProjects/Communications/VS_Project/ISCommunicationsExample.vcxproj, ExampleProjects/Logger/VS_Project/ISLoggerExample.vcxproj, ExampleProjects/NTRIP_rover/VS_Project/ISNtripRoverExample.vcxproj, VS_project/InertialSenseLib.vcxproj, cltool/VS_project/cltool.vcxproj
With update of my laptop, updating our dev tools made sense.  VS2017 is out of date.
=> Update projects to build in VS2019 and QT 5.15.2

src/data_sets.h, src/protocol_nmea.cpp, src/protocol_nmea.h
This addresses an issue we discovered in Fortem's data where GPS2 which didn't have an antenna connected reported a bogus ECEF velocity when the speed accuracy (sAcc) said it was valid yet the GPS position did not have fix and the GPS time was obviously incorrect.
Now we use the same status flags from GPS pos in the GPS vel message so we can use the GPS position status to validate the GPS velocity.
=> Improve GPS velocity validation

src/ISTcpClient.cpp, src/InertialSense.cpp
- fixes a small memory leak that could occur if the connection is attempted to be opened multiple times 
- fixes return values for non-blocking socket connection status
Supports 
https://github.com/inertialsense/inertial-sense-ros/pull/84
=> SN-503 memory leak fix

EVB-2/IS_EVB-2/IS_EVB-2.cppproj, EVB-2/Makefile
The XDMA handler is not found and a hard fault occurs when d_dma.c is not included in the project.
=> LUNA-1904 Added d_dma.c to gcc Makefile

EVB-2/IS_EVB-2/src/communications.cpp
When using white config it's more useful to have a true passthrough (IMO) instead of everything parsed for IS packets. All of that can be done using any of the other presets. This also makes the EVB2 a more useful USB-Serial converter.
=> Bypass IS parsing EVB2 firmware

EVB-2/IS_EVB-2/src/communications.cpp, ExampleProjects/Bootloader/ISBootloaderExample.c, ExampleProjects/Bootloader/README.md, cltool/VS_project/cltool.vcxproj.user, src/ISDisplay.h, src/InertialSense.cpp, src/InertialSense.h, src/cltool.cpp, src/cltool.h, src/cltool_main.cpp, src/inertialSenseBootLoader.c, src/inertialSenseBootLoader.h
- Fixed issues with using cltool to update bootloader firmware.
- Remove old unused code from bootloader.  Updating bootloader firmware must be done along with updating application firmware.
- Consolidated application and bootloader firmware update in cltool.
- Added -fb forceBootloaderUpdate option to cltool.
- Fix failed to update firmware error status.
- Added error checking to catch invalid filename or if force update option is supplied without a file name. 
- Change return state of bootloadFileEx() to 0 on success, -1 on failure.
=> SN-968 Clean up bootloader

src/message_stats.cpp, src/message_stats.h
This fixes the following errors when building python log inspector:
```
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fPIC -Iinclude -I../src -I../../src -I/usr/lib/python3.9/site-packages/pybind11/include -I/usr/lib/python3.9/site-packages/pybind11/include -I/usr/include/python3.9 -c ../../src/message_stats.cpp -o build/temp.linux-x86_64-3.9/../../src/message_stats.o -O3 -DVERSION_INFO="0.0.1" -std=c++14
../../src/message_stats.cpp: In function ‘void messageStatsAppend(std::string, mul_msg_stats_t&, int, int, int)’:
../../src/message_stats.cpp:114:14: error: narrowing conversion of …
```
=> fixes for building logInspector

src/ISDisplay.cpp, src/ISDisplay.h, src/cltool_main.cpp
This fixes a screen refresh problem with the CLtool, introduced recently when I added the ability to the CLTool to set write only DIDs.
=> Fixed issue where RTK base info would scroll at bottom

hw-libs/misc/rtos.c
The method to put the Microchip and STM32 chips we have in our products are almost exactly the same. I broke out the calls in the pmc_enable_sleepmode function. @rudomorg, I need your help to test the following:
- uINS-3 power consumption with the sleep lines commented and uncommented
- uINS-5 power consumption with the sleep lines commented and uncommented
Once we can confirm that these lines are indeed putting us into sleep mode, we can go ahead and merge this.
=> SN-1004 Update idle task to work on uINS-5

src/inertialSenseBootLoader.c
This fixes an issue where the bootloader would update to older version of bootloader when it shouldn't.  It should downgrade if the FORCE option is used.
=> SN-1313 bootloader update version detect bug

src/inertialSenseBootLoader.c
This adds support for the v5a bootloader to our SDK, preventing bootloader incompatibility for customers that have v5a.
=> SN-1534 Add support for v5a bootloader

src/data_sets.h
This fixes ability to read RTK GPS over external port by moving the "no init" option to a separate bit.
=> SN-1800 Create separate noInit option from gpsType

EVB-2/IS_EVB-2/src/communications.cpp, EVB-2/IS_EVB-2/src/globals.c, EVB-2/IS_EVB-2/src/globals.h, EVB-2/IS_EVB-2/src/user_interface.cpp, src/data_sets.h
Currently flash writes happen every second on the second if enabled and needed.  
This adds 1 second delay to all flash writes to allow grace time and reduce likelihood that a sequence of flash config changes will cause a flash write and data drop in middle of the sequence of flash writes.
=> SN-1872 Add 1s delay following last flash write to reduce likelihood of data drop

src/data_sets.h
Help manufacturing to easily identify if units have been motion calibrated or not.
=> Added calibration valid bits to DID_SCOMP.status

src/ISClient.cpp
When `getaddrinfo` fails, the `cISTcpClient` returns `getaddrinfo` error code (see [here](https://github.com/inertialsense/inertial-sense-sdk/blob/a04077f075d432dec6dbccfabefdddf68ace2030/src/ISTcpClient.cpp#L258)), which can potentially be different from `-1`. In such a case, it should not report a successful connection.
=> [ISClient] Fail even if getaddrinfo fails

src/ISBootloaderISB.cpp, src/ISDataMappings.cpp, src/data_sets.h, src/pybindMacros.h, src/serialPortPlatform.c
Allow GPS PPS input on IMX-5 PPS TIMEPULSE (pin 20).  
Add status indicators to identify if PPS is valid or if there is an error.
=> SN-2254 gps timepulse support

src/ISBootloaderBase.cpp, src/ISBootloaderBase.h, src/ISBootloaderISB.cpp, src/ISBootloaderThread.cpp
- Fix hang at end of application update when DFU update is executed before (`m_libusb_devicesActive = 0;` needed to be called)
- Comments and variable names
- Timings
=> SN-2284/SN-2285 Fix conditions needed to update bootloader

src/data_sets.h
This changes the `flash write` indicator to `flash write pending` to indicate that the flash write will occur at the when the indicator turns off.
=> Change status indicator to flash write pending

python/logInspector/logReader.py
Latest changes broke the ability to plot Novatel data without any other devices in the log.
=> Plot novatel alone

src/DataKML.cpp, src/DataKML.h, src/DeviceLog.cpp, src/DeviceLog.h, src/DeviceLogKML.cpp, src/DeviceLogKML.h, src/ISLogger.cpp, src/ISLogger.h
This changes the color of the reference INS line in the KML data (Google Earth) image so we can tell when the SPAN is in dead reckoning mode.
=> Add separate color for ref INS dead reckoning mode in KML

src/ISDataMappings.cpp, src/data_sets.h
Add strobe input option for G15 (GPS1 PPS).  Adds options to indicate EKF reference point is stationary.
=> SN-2699 signal ref point stationary

EVB-2/IS_EVB-2/IS_EVB-2.cppproj, EVB-2/IS_EVB-2/src/communications.cpp, EVB-2/IS_EVB-2/src/globals.c, EVB-2/IS_EVB-2/src/globals.h, EVB-2/IS_EVB-2/src/misc/init.c, EVB-2/IS_EVB-2/src/user_interface.cpp, src/data_sets.h
Fixes an issue where the flash write needed on startup does not happen because time_msec() returns zero from booting too quickly.
=> SN-2757 evb2 startup flash write

ExampleProjects/NTRIP_rover/ISNtripRoverExample.cpp, src/ISDisplay.cpp, src/cltool_main.cpp, src/data_sets.h, src/protocol_nmea.cpp
Address confusing ambiguity of gps status flags that are found in both gps1pos.status and gps2pos.status.  These flags that were renamed are common in both locations but specific to GPS1 and GPS2 specific.  GPS status values defined in enum eGpsStatus were renamed to clarify GPS1 or GPS2 association.
=> Renamed gps status flags to clafify GPS1 or GPS2 association

EVB-2/IS_EVB-2/src/communications.cpp, EVB-2/IS_EVB-2/src/config/FreeRTOSConfig.h, hw-libs/boards/EVB-2.h, hw-libs/freertos/stream_buffer.c, hw-libs/misc/rtos.c
All of our projects with FreeRTOS were throwing this warning. Only the EVB-2 uses stream buffers, so the fix was two-fold:
1. On the EVB-2, switch to statically allocated stream buffers. This completely avoids the issue with alignment. If you read the FreeRTOS source code, they assume that malloc is aligned, which I'm not a fan of. I put an `#if 0` ... `#endif` around dynamically allocated stream buffers. I had to decrease the heap size to account for the buffers being allocated statically.
1. On our internal projects, don't compile the `stream_buffers.c` file (see PR in internal repo) and disable stream buffers in the `FreeRTOSConfig.h` file.
```
../hw-libs/freertos/stream_buffer.c: In function 'xStreamBufferGenericCreate':
../hw-libs/freertos/stream_buffer.c:288:43: warning: cast …
```
=> Fix compiler alignment warnings for FreeRTOS stream buffer

python/logInspector/logInspector.py
Since the python dependency version is not locked in `setup.py`,  the `pip install logInspector/` will always install the latest version python dependency . This commit will fix logInspector for the current latest PyQt5 5.15.7.
I suggest we lock the python dependency version.
=> Fix logInspector for PyQt5 5.15.7

ros/src/inertial_sense_ros.cpp, src/ISEarth.c, src/ISEarth.h, src/convert_ins.cpp
Including all version of ecef2lla takes allot of instruction space memory.  This reduced the selected version to compile time and still allows the application to select which version to use.
=> Optimize ecef2lla

src/com_manager.h
Increase maximum number of broadcast non-RMC messages.
=> Increase MAX_NUM_BCAST_MSGS from 4 to 12

src/InertialSense.cpp, src/InertialSense.h, src/cltool_main.cpp
Decouple SDK tcp connection close from device close in InertialSense class.  We shouldn't be closing the TCP connecting if the device serial port closes.
=> SN-3019 sdk tcp corrections bug

python/logInspector/logInspector.py, python/logInspector/logInspectorInternal.py, python/logInspector/logPlotter.py
- Adds an icon to the taskbar in Windows that was previously missing. The way we were using the QMainWindow class wasn't working with some other parts of Qt related to this. 
- Adds a handler for Ctrl-C in the terminal. Qt doesn't let the terminal do anything after the exec() call, so we set a timer for 5Hz and let the system manage interrupts at that interval.
- Clean up warning in terminal related to improper usage of Qt image classes
=> logInspector icon and terminal improvements

src/ISBootloaderISB.cpp
Fixed an issue where the connected device is not properly detected inside the `check_is_compatible()` function on a Windows machine.  A stray byte is received which prevents proper detection of the connected device.  Addition of serialPortRead() ensures the Rx buffer is completely empty.
=> Ensure buffer is empty before read

src/data_sets.h, src/protocol_nmea.cpp, src/protocol_nmea.h
Allow standard NMEA messages to have configurable talker ID.  GNSS ID "$GNxxx" is used if multiple constellations are selected, or the constellation specific talker ID is used if a single GNSS constellation is selected (i.e. $GPGGA for GPS).
=> SN-3703 standard NMEA use gn

src/ISDataMappings.cpp, src/ISDisplay.cpp, src/data_sets.h, src/protocol_nmea.cpp, src/pybindMacros.h, src/test/test_protocol_nmea.cpp
Add build type (alpha, beta, release candidate, release, debug) to dev_info_t.  Convert buildDate and buildTime to specific names (year, month, day, hour, minute, second, etc.).
=> Add build type and call out build date and time

src/data_sets.c, src/data_sets.h
As part of the fix for DID_RMC data stream bug: Use lookup table for DID to RMC bit conversion.
=> SN-3765 Replace didToRmcBits() switch with lookup table

src/ISBootloaderThread.cpp
Fortem was reporting issues upgrading from 1.8. The issue was looked into and eventually, the difference was found that were using a UART to USB FTDI part versus our normal workflow of using the built-in USB CDC. This caused the full update(Bootloader and Application) to run beyond the 120-second maximum update time, approximately 147 seconds running at default baud(921600). This maximum time was increased to 180 seconds for the default baud. Any other supported baud has a maximum time of 360 seconds. This was tested with the FTDI at the minimum supported baud (115200). Run time of the minimum baud was apporximatly 220 seconds.
=> Sn 3991 FTDI update time out 

ros/include/inertial_sense_ros.h, ros/launch/example_params.yaml, ros/launch/test_config.yaml, ros/launch/test_ros_bridge.launch, ros/src/inertial_sense_ros.cpp, ros/test/test_communications.cpp, ros/test/test_main.cpp, src/InertialSense.cpp, src/InertialSense.h, src/cltool.cpp, src/cltool.h, src/cltool_main.cpp, src/data_sets.h
ioConfig and platform no longer need to be set by unless they are used to overwrite the default in flash config.  With the platform type in OTP memory, the factory default settings will ensure ioConfig is correct for the GPS configuration.
=> SN-4050 fix ros flash config sync

src/com_manager.c
A hard fault was caused by an index out-of-bounce exception when GPX flash config was requested. This is because the did is 121 which tries to access an array of 100 elements. The check that was already in place only checked that the value was non-zero.
=> check index out of bounce issue

src/ISFirmwareUpdater.cpp
Add 10ms (15ms total) to each fnWrite in ISFirmwareUpdater.cpp to reduce overruns (but still keep moving).
=> Forced latency to reduce lost FirmwareUpdate packets.

src/ISComm.c, src/ISComm.h, src/com_manager.c, src/com_manager.h, src/test/CMakeLists.txt, src/test/setup_debug.sh, src/test/test_ISComm.cpp
Revise v2 protocol packet parser to only parse one packet at a time (no concurrent parsing anymore).  We only care to parse the highest level packets.  Packet parsing is invalidate either by 1.) exceeding max packet length or 2.) incomplete packet received by timeout.  The prior method of allowing concurrent parsing was a bad idea as it allowed encapsulated packets (packets inside packets) to invalidate the outer packet parse.
=> Sn 4293 iscomm parser refactor

src/ISSerialPort.cpp
Change how we populate cISSerialPort::GetComPorts() to use all currently available functional serial ports in Linux.
=> Include only available serial ports

src/ISFirmwareUpdater.cpp, src/protocol/FirmwareUpdate.cpp, src/protocol/FirmwareUpdate.h
Fixed DID_GPS2_VERSION reporting GNSS1 version.
Moved debug printing behind DEBUG_LOGGING macro in CXD5610 driver.
Fixed error strings in FirmwareUpdate, and additional minor refactors.
Fixed error fault/reporting in ISFirmwareUpdater.
Removed some unused variables/functions (reducing warnings)
Moved some static, internal variables into member variables (which need to be instance specific).
=> SN-3972 Multi-Target Firmware Updates

src/ISFirmwareUpdater.cpp, src/ISFirmwareUpdater.h, src/InertialSense.cpp, src/cltool_main.cpp, src/protocol/FirmwareUpdate.cpp, src/protocol/FirmwareUpdate.h, src/test/test_ISFirmwareUpdate.cpp
Also, a couple of light refactors to support new functionality.
This is a pretty direct PR, with most of the changes as new code in ISFirmwareUpdater.cpp that provides a mechanism for parsing a "Package Manifest" YAML file, and generating a series of commands for ISFirmwareUpdater to process in order to update the requested files.
The other major change was refactoring the command processor out to its own function, to help reduce the complexity of the original function, and to better isolate the "command code" from the "update code".
Also reworks the REQ_RESET command in the FirmwareUpdate API so that it actually works, and has some additional flexibility to pass "reset flags" to help drive specific reset-related behaviors.
=> Adds initial support for Firmware Package (via manifest.yaml)

EVB-2/IS_EVB-2/IS_EVB-2.cppproj, EVB-2/IS_EVB-2/src/communications.cpp, EVB-2/IS_EVB-2/src/misc/init.c, hw-libs/drivers/SAMx70/ASF/sam/drivers/uart/uart.c, hw-libs/drivers/SAMx70/ASF/sam/drivers/uart/uart.h, hw-libs/drivers/SAMx70/d_serial.c, hw-libs/drivers/SAMx70/d_serial.h, src/ISComm.c, src/ISComm.h, src/ISConstants.h, src/InertialSense.h, src/cltool.cpp, src/protocol_nmea.cpp
- (IMX) UART baudrate can now be set to arbitrary custom non-standard baudrates when greater than 921600 bps to improve compatibility with host UARTs.  When >921600 bps, the `DID_FLASH_CONFIG.serXBaudRate` parameter is automatically adjusted to the closest available baud rate in order to inform the user of the actual hardware baud rate.    
- (EvalTool, cltool, SDK) Serial port can now be set to custom non-standard baud rates above 921600 bps. 
- (IMX) Fixed non-standard high speed UART baud rates greater than 921600 bps.  Now supporting up to 10 Mbps on the IMX-5 UART. 
- (IMX) Fixed RMC options to set multiple ports besides RMC_OPTIONS_PORT_ALL and RMC_OPTIONS_PORT_CURRENT.
=> Fix high speed baud rates

src/ISDisplay.cpp, src/cltool_main.cpp
- (cltool) Fix issue where `cltool -flashCfg` returns all zeros because DID_FLASH_CONFIG had not been queried.  
- (cltool) Fixed seg fault in ISDisplay DataSetToString for uninitialized data pointer.
=> SN-4422 cltool flash cfg zeros seg fault

src/ISComm.c, src/data_sets.h
Fixed issue in ISComm where parsing packets that contain a data offset did not correct the size of the actual data in the header.   rxPkt.hdr.payloadSize and rxPkt.dataHdr.size share same memory in the packet through a union.  The packet full payload sized in contained in this value but needs to be reduced by 2 bytes if there is an offset so that it properly reflects the data size not included the offset.  This issue incorrectly caused two extra bytes to be written to the destination when the offset was non-zero.
=> SN-3702 gps imx not passing rms

src/ISFirmwareUpdater.cpp, src/ISFirmwareUpdater.h, src/protocol/FirmwareUpdate.cpp, src/protocol/FirmwareUpdate.h, src/test/test_ISFirmwareUpdate.cpp
Adds the ability to use .fpk file extensions while updating GPX GNSS receivers.
Fixes bug with checksum where 0 length data would cause an invalid checksum.
=> Sn 4508 add ability to send fpk files

src/data_sets.h
SN-4427 Move default GPS configuration from IO_CONFIG_DEFAULT to nvm_flash_cfg_defaults().
=> Move default GPS type from IO_CONFIG_DEFAULT to nvm_flash_cfg_defaults()

src/InertialSense.cpp, src/cltool.cpp, src/serialPort.h, src/serialPortPlatform.c
Additional checking, validation and reporting on serialPortPlatform.c.
Invalid or errant devices which fail a basic read() test will be closed immediately (inside call to serialPortPlatformOpen).
Additional check in InertialSense.cpp will remove discovered devices if they also fail a write() test.
Note, this is purely an SDK improvement, but still need an IMX PR for the SDK bump to be ran through CI-HDW checks.
=> More complete fix to prevent serial write() from blocking indefinitely.

ExampleProjects/IS_firmwareUpdate_v2/ISFirmwareUpdateExample_v2.cpp, src/InertialSense.cpp, src/InertialSense.h, src/cltool_main.cpp, src/serialPortPlatform.c
Identified an issue, primarily in the cltool, in which it would require a binary response from connected devices, before sending the $info query for device info. This would prevent the device from initializing correctly, and thus identifying the device. 
I modified the requirements for “device validation”, which ONLY relies on dev_info_t being populated (requested via $info).  Once validated, additional requests are made for the flash config, etc.  In addition, extra validation is performed, with improved reporting from the cltool if discovered devices are not COMPATIBLE with the current protocol version (2).  In this instance, cltool will report the error and the DEVINFO for all discovered devices (so the user can see which devices are compatible).
Note that the way devices are currently …
=> SN-4676 Addresses device discover of v2 protocol devices, particularly for cltool.

src/ISFileManager.cpp, src/ISFileManager.h, src/ISFirmwareUpdater.cpp, src/ISFirmwareUpdater.h, src/cltool.cpp, src/protocol/FirmwareUpdate.cpp, src/protocol/FirmwareUpdate.h, tests/test_ISFirmwareUpdate.cpp
But you should now be able to update any GPX version > 2.0.0.7 forward, with the latest EvalTool/Cltool without issues.  See JIRA SN-4797 for specifics.
=> Resolve backward compatibility issues with SDK tools and FirmwareUpdate

src/cltool_main.cpp
... when cltool_firmwareUpdateInfo() has no or null message string.
=> Quick fix for Cltool segfault

src/data_sets.h
This will allow users to disable L1 or L5 freq along with constellations.
=> SN-4893 Allow separate config for L1 L5 gnss const

src/data_sets.h
Our magnetometer units are not gauss.  They are normalized to 1 for the strength of the earths magnetic field in Utah.  This removes the "gauss" label which may confuse some customers.
=> Remove reference to gauss for magnetometer units

src/data_sets.h
(GPX) Changes state machine timers for GNSS init to work properly during edge case scenarios.
=> Sn 4895 add init state timer cxd

src/ISDisplay.cpp, src/InertialSense.cpp, src/InertialSense.h, src/cltool.cpp, src/cltool.h, src/cltool_main.cpp
This fixes a problem where the cltool -flashCfg would return zero.  This was cause by recent changes to handshaking when the serial port is opened in the inertialsense class and not requesting and waiting for DID_FLASH_CONFIG to be received.  This also removes some EVB code from cltool.
=> Wait until flash config is received before printing.

src/ISConstants.h, src/data_sets.h, src/protocol_nmea.cpp, src/pybindMacros.h, src/test/test_protocol_nmea.cpp
Address complications of having zero as a valid NMEA message ID.  Shift all NMEA message IDs up and make ID zero an invalid ID.  
Allows $ASCE to accept NMEA identifier name instead of the NMEA message ID.  The following two statements enable the same NMEA messages:
```
$ASCE,0,PPIMU,1,PINS2,10,GxGGA,1*10\r\n
$ASCE,0,2,1,5,10,7,1*39\r\n
```
=> SN-4962 remove nmea msg id zero

src/ISConstants.h, src/data_sets.h, src/protocol_nmea.cpp, src/pybindMacros.h, tests/test_protocol_nmea.cpp
Address complications of having zero as a valid NMEA message ID.  Shift all NMEA message IDs up and make ID zero an invalid ID.  
Simplifies DID_NMEA_BCAST_PERIOD (nmea_msgs_t) by removing msgCount.
Allows $ASCE to accept NMEA identifier name instead of the NMEA message ID.  The following two statements enable the same NMEA messages:
```
$ASCE,0,PPIMU,1,PINS2,10,GxGGA,1*10\r\n
$ASCE,0,2,1,5,10,7,1*39\r\n
```
=> Sn 4962 remove nmea msg id zero v2

src/protocol_nmea.cpp, tests/test_protocol_nmea.cpp
Lat/Lon direction determination was based on integral degrees, instead of fractional.  Fixed.
=> SN-5022 - $GNGGA Lat/Lon Direction

cltool/src/cltool.cpp, src/ISDataMappings.cpp, src/ISDataMappings.h
Tries to protect against unaligned-variable assignments on Armv7.
Added support to query/print single flashCfg parameters.
=> Fix/SN-5028 Cltool FlashCfg errors

src/data_sets.h
Create SYS_CMD_GPX_SOFT_RESET_GPX (similar to SYS_CMD_GPX_HARD_RESET_GNSS1) as a way to issue a GPX reset through the IMX.
=> Add a sys cmd to reset GPX through IMX

python/logInspector/logInspector.py, src/ISComm.c, src/ISLogger.cpp, tests/test_data_utils.cpp
- Fix test_data_utils.cpp build in Windows caused by variables defined within a switch statement.
- Fix LogInspector's ability to queue dataInformation.json used for the NavProcess post processing project for logs with serial numbers oflength different than 5 digits and .raw logs.
=> SN-5030 fix evaltool windows build

cltool/src/cltool.cpp, cltool/src/cltool.h, cltool/src/cltool_main.cpp, scripts/windows/build_sdk_examples.bat, src/DeviceLog.cpp, src/InertialSense.cpp, src/data_sets.h, src/util/natsort.cpp, src/util/natsort.h, src/util/util.h
Implement "--list-devices" (or -list-devices) in clTool to discover all Inertial Sense devices, their hardware and firmware information, and print the results in a natual sorted order by port name:
```$ ./cltool --list-devices
/dev/ttyACM0 --> SN62842, IMX-5.0 (fw2.0.3 37c)
/dev/ttyACM1 --> SN62855, IMX-5.0 (fw2.0.3 37c)
/dev/ttyACM2 --> SN62850, IMX-5.0 (fw2.0.3 37c)
/dev/ttyACM3 --> SN62849, IMX-5.0 (fw2.0.3 37c)
/dev/ttyACM4 --> SN62806, IMX-5.0 (fw2.0.3 37c)
/dev/ttyACM5 --> SN62844, IMX-5.0 (fw2.0.3 37c)
/dev/ttyACM6 --> SN62833, IMX-5.0 (fw2.0.3 37c)
/dev/ttyACM7 --> SN62832, IMX-5.0 (fw2.0.3 37c)
/dev/ttyACM8 --> SN928398908, GPX-1.0 (fw2.0.6 233r)
/dev/ttyACM9 --> SN928396093, GPX-1.0 (fw2.0.6 233r)
/dev/ttyACM10 --> SN928399420, GPX-1.0 (fw2.0.6 233r)
/dev/ttyACM11 --> …
```
=> SN-5124 - Implements "-list-devices" in cltool

python/pylib/ISToolsData.py, src/ISConstants.h, src/ISDataMappings.cpp, src/ISDevice.cpp, src/ISDevice.h, src/ISDisplay.cpp, src/ISFirmwareUpdater.h, src/InertialSense.cpp, src/InertialSense.h, src/data_sets.h, src/pybindMacros.h
This is kind of a superficial change on the ISDevice side, which basically moves `is_device_t` into proper class called `ISDevice`. It also moves `is_firmUpdate_info_t` into a class called `ISDeviceUpdater`.
ISDevice consolidates all information associated with an Inertial Sense device, outside of the InertialSense class (though, that is where its still primarily used).  Specifically, it makes a hard association between the devInfo, flashConfig, serialPort and portHandle, and also the device update status (through ISDeviceUpdater) available through the ISDevice class.
Because ISDevice is not an internal class of the InertialSense class, you can now request from the InertialSense class, a pointer to the ISDevice, and have access to all necessary data, handles, etc to be able to directly …
=> SN-4901 ISDevice + UpTime to SYS_PARAMS & GPX_STATUS

src/data_sets.h
We want to help users better identify when the INS is dead reckoning.
=> Help users know dead reckoning is running

scripts/install_pybind.sh, src/InertialSense.cpp
This fixes a problem that prevents scripts/install_pybind.sh from working inside of virtual environments,
It also fixes a bug inside of the SDK that can cause OpenSerialPorts() to loop forever when a serial port doesn't respond
=> Fix General SW Linux Build

python/logInspector/setup.py, scripts/install_pybind.sh
Fixes some GitHub Actions errors related to building Log Inspector on GitHub Action Runners related to missing pybind11 during LogInspector Package setup.
also fixes a non fatal error related having the wrong path for `scripts/build_cmake_tests.sh` in `scripts/install_pybind.sh`
=> SN-5270 Fix Action Runner Log Inspector Build

src/ISLogger.cpp, tests/test_ISLogger.cpp
Fixed cISLogger crash caused by reading file with no numerical characters in filename.  This prevents LogInspector from being able to open certain logs.
=> SN-5245 loginspector cant open raw

ExampleProjects/Arduino/ReadIS/ReadIS.ino, ExampleProjects/Communications/ISCommunicationsExample.c, ExampleProjects/Communications/README.md, ExampleProjects/NTRIP_rover/README.md, src/ISComm.c, src/ISComm.h, src/InertialSense.cpp, src/com_manager.c, src/serialPortPlatform.c
Address issue in ISComm where the return value needs to be different for the following functions:
- **is_comm_write()** and related functions that writes directly to the serial port should.  These should return success or failure because the results are not recoverable as multiple serial port writes occure. 
- **is_comm_write_to_buf()** and related functions that write into a buffer should return the number of bytes written into the buffer so that the caller can properly send the message.
=> SN-5281 fix ISComm function return

ExampleProjects/Arduino/ReadIS/ReadIS.ino, ExampleProjects/Communications/README.md, ExampleProjects/Communications/setup_debug.sh, src/ISComm.c, src/ISComm.h, src/data_sets.h, tests/test_ISComm.cpp
This PR matches the parameter order of size and offset in functions is_comm_get_data() and is_comm_get_data_to_buf().
In the release 2.x, similar functions were refactored to have consistent parameter order of did, size, offset.  These less commonly used functions were overlooked.
=> Match convention of size and offset parameter order

src/ISComm.c, src/ISComm.h
Support for reference IMU use with Lambda and TBED-3.
Added is_comm_data_pkt() to ISComm as a way to access the packet_t used for sending data without having to copy into a buffer.   
Move simple function calls to static inline in ISComm.h
=> SN-3376 sensonor lambda support for TBED-3

src/ISComm.c, src/ISDataMappings.cpp, src/data_sets.h, src/pybindMacros.h
Fixed issue in which serial loopback in manufacturing testbed causes the DID_BIT to erroneously cancel.   Separated BIT input command from BIT state to prevent BIT output status from incorrectly overwriting the BIT command.
=> SN-5328 bit not working

src/ISDisplay.cpp, src/ISDisplay.h, src/data_sets.h
Also Fixes a bug in which a lack of DataSets data for a DID could cause a SEGFAULT or invalid memory access.
=> SN-5344 Adds cltool support DID_PORT_MONITOR

.gitignore, scripts/build_log_inspector.sh, scripts/install_log_inspector_dependencies.sh, scripts/lib/python_venv.sh
This should make it so that when building Log Inspector or installing Log Inspector's dependencies it will automatically locate or create a virtual environment if one can't be found
It also adds .venv to .gitignore so no one accidentally uploads a Python virtual environment to GitHub
=> SN-5332 Automatic Python Virtual Enviroments

ExampleProjects/Communications/ISCommunicationsExample.cpp, cltool/src/cltool.cpp, cltool/src/cltool_main.cpp, src/ISComm.c, src/ISComm.h, src/InertialSense.cpp, src/com_manager.h, tests/test_ISComm.cpp, tests/test_com_manager.cpp, tests/test_com_manager_2.cpp, tests/test_serial_utils.cpp, tests/test_serial_utils.h
Switch the serial port number function parameter from signed int to unsigned int.  This addresses a problem where a negative serial port number caused an invalid Tx overlow indication and indexed out of bounds in the port monitor array.  Rather than try to catch a negative serial port number in all of the cases where it may be problematic, we switch it to an unsigned int.  We have no need for a negative serial port number.
=> SN-5304 unsigned serial port number

ExampleProjects/Communications/ISCommunicationsExample.cpp, cltool/src/cltool.cpp, cltool/src/cltool_main.cpp, src/ISComm.c, src/ISComm.h, src/InertialSense.cpp, src/com_manager.h, tests/test_ISComm.cpp, tests/test_com_manager.cpp, tests/test_com_manager_2.cpp, tests/test_serial_utils.cpp, tests/test_serial_utils.h
Switch the serial port number function parameter from signed int to unsigned int. This addresses a problem where a negative serial port number caused an invalid Tx overlow indication and indexed out of bounds in the port monitor array. Rather than try to catch a negative serial port number in all of the cases where it may be problematic, we switch it to an unsigned int. We have no need for a negative serial port number.
=> SN-5352 unsigned serial port

src/data_sets.h, src/protocol_nmea.cpp, src/protocol_nmea.h
(SDK) Fixed bug where GxGSV would be mangled on non-GPS constellations.
(GPX) Fixed bug when DID_GPX_PORT_MONITOR reports invalid values for port 0 (SN-5363).
(GPX) Added reset reason to DID_GPX_STATUS
=> Sn 5349 save gpx fault reason

scripts/build_log_inspector.sh, scripts/install_log_inspector_dependencies.sh
Only use the --break-system-packages option with python 3.11 and later.
=> Only use --break-system-packages with python 3.11 and later

python/logInspector/src/log_reader.cpp, src/data_sets.h
SN-5346 manufacturing support for 2.x software.  Separate CAL_BIT_FAULT_MCAL_INVALID into CAL_BIT_FAULT_MCAL_IMU_INVALID and CAL_BIT_FAULT_MCAL_MAG_INVALID.  Print SDK protocol version from log_reader.
=> SN-5346 manufacturing support for 2.x software

src/ISDisplay.cpp
Cltool/ISDisplay now report “RESET REQUIRED” “TX LIMITED” and “RX OVERFLOW” in addition to showing the FlashCfg checksum.
=> SN-5366 - Cltool to show hdwStatus and flashCfgChecksum

src/InertialSense.cpp, src/InertialSense.h, src/data_sets.h, src/imx_defaults.c, src/imx_defaults.h
Fixed issue where flash config sync would not update checksum correctly and perform unnecessary flash sync if platformConfig type was unchanged.  Ignore bit PLATFORM_CFG_UPDATE_IO_CONFIG when checking whether to upload flash config platformConfig from InertialSense class.
=> SN-5441 flash config sync platform

src/DeviceLogCSV.cpp
Fix EvalTool log conversion tool.  Prevent access to uninitialized device pointer.
=> SN-5391 evaltool file conversion issues

src/data_sets.h
Only show reference IMU error if it was received at least once and then stop being received.
=> Hide reference IMU

cltool/src/cltool_main.cpp, src/ISComm.c, src/ISComm.h, src/ISDisplay.cpp, src/ISDisplay.h
- Fix `-did x` option stops streaming when message was previously streaming. 
- Prevent reception of stray data by disabling cltool_dataCallback() until stop broadcast in cltool_setupCommunications() is called. This prevents the cltool from processing any data received prior to cltool_setupCommunications().
- Simplify data request to be more robust, re-requesting data once a second. 
- Fix `-edit` option not displaying.  Copy data into m_editData.pData.pDataBuf to ensure large data sets at high rates do not get mangled when print to display. 
- Fix `-edit` option variable selection.  
- Reformat print of DID_GPX_STATUS state variables for readability.
=> SN-5612 Fixed multiple cltool issues

.github/workflows/main.yml, ros/src/inertial_sense_ros.cpp, ros/test/test_basic_unit_tests.cpp, ros/test/test_communications.cpp, ros/test/test_main.cpp
- **_Disabled_** the gps time sync test for now because of non-determinist characteristics. This will be fixed in a future issue.
- Modified the workflow so tests are called in standard ROS way.
- Added protection for a false connection to unit. 
- Fixed a vector out of bounds access (.end() used in place of .back())
- Added protection around calling non-defined pusblishers.
=> Fixes to Pass ROS bridge tests

cltool/src/cltool.cpp, cltool/src/cltool.h, cltool/src/cltool_main.cpp, src/data_sets.h
- Renamed `asciiMessages` to `nmeaMessage`.
- Added `-nmea` option to cltool help menu.
- Print to screen sent NMEA message with checksum footer.
=> Add -nmea option to cltool

src/ISDisplay.cpp, src/ISFirmwareUpdater.cpp, src/InertialSense.cpp, src/com_manager.h, src/protocol/FirmwareUpdate.cpp, src/protocol/FirmwareUpdate.h, src/util/util.cpp, src/util/util.h, tests/test_com_manager.cpp
Updated com_manager.h callback typedefs to be consistent with other similar callbacks (return int).
Updated InertialSense class to use to new com_manager callback signatures, returning 0 on success, and -1 on error.
Updated iomanager static callbacks to match com_manager.h callback signatures. 
Added callback into evaluation.cpp for InertialSense instance used for FirmwareUpdateDialog.
Fixed FirmwareUpdate:requestUpdate() to save/rerequest the progress rate to the session; set default to 250ms.
Added step/command error reporting for each device updated in EvalTools' FirmwareUpdateDialog.
Removed unnecessary "COM port open!" message from FirmwareUpdateDialog.
Fixed ISFirmwareUpdater using TARGET_HOST when using legacy step names old manifests. Legacy step names now correctly specify the …
=> Fix/SN-5371 Broken EvalTool fwUpdate

src/ISBootloaderISB.cpp
Correctly calculates the number of available logical pages of flash for application firmware, including partial pages.
Removes (temporarily) error/failure when trying to write to the last partial "logical page" of application flash memory.
=> Sn 5745 - ISbootloader can't access last 32kb

src/ISDataMappings.cpp, src/data_sets.h
Revert GPX flash config size.  Use gpx_flash_cfg_t::debug as the surrogate storate for variable that were removed.  See line 47-50 in globals.h for bit definitions.
=> SN-5733 Revert gpx flash config size

tests/test_ISLogger.cpp
Previous update to unit tests introduced a EXPECT_EQ() from a pair of doubles, which is generally bad.  This fixes that with EXPECT_DOUBLE_EQ, which seems to work (but may need to be switch to a EXPECT_NEAR()
=> SN-5793 - Fix test_ISLogger

python/logInspector/logInspector.py, python/logInspector/logPlotter.py, src/ISLogger.cpp, src/ISLogger.h, tests/test_ISLogger.cpp, tests/test_data_utils.cpp
- Add option to LogInspector to toggle X-axis from timeOfWeek to message index to better identify system reset(s).
- Increase  csv output file size from 5MB to 50MB in EvalTool log conversion tool.
=> SN-5802 - Log Inspector Improvements

src/data_sets.h
In d_dma when dma_tx_free() results in a negative number handle gracefully and report.
=> SN-5865: Add DMA fault logging.

src/data_sets.h
This is just adding white space to clarify that  the comments the message data rates, not the bits. The whitespace aligns the comments so it better indicates this.
=> Align data rate for readibility

src/DeviceLog.cpp
Bug fix. Exception in DeviceLog.cpp due to calling back() on an empty vector.
=> SN-5925 Exception in DeviceLog

src/ISLogger.cpp, src/ISLogger.h
Delete cISLogger::DeviceLogBySerialNum() and use cISLogger::DeviceLogBySerialNumber() instead.
=> Remove DeviceLogBySerialNum

src/data_sets.h
Added define for IMX->GPX pairing RMC define to allow separation of GPS1/2 msgs for base messages.
=> SN-5767 Update defines to allow GPS port disabling

scripts/windows/build_run_log_inspector.bat, src/ISComm.h
Increase the length by one of the generic callback function array so that the sony binary index can be included.
=> SN-5942 fix is_comm generic callback array size

src/ISDevice.cpp, src/ISDevice.h, src/serialPortPlatform.c
- Removed some RTK config bits from ISDevice flashConfig validation (which may be set programatically).
- ISDevice helper functions SendData(), SendRaw() and others which make port-write() calls return the port-write result for proper error checking.
=> SN-5908 - Add RTOS info to Grafana

python/setup.py
Removed requirement for Allantools to be below v. 2019
=> SN5953 allow latest allantools in loginspector

src/ISConstants.h, src/ISEarth.c
Pretty basic refactor; @aabogdanov we should probably consider refactoring a number of the constant variables in ISEarth.c to be more meaningful names, but totally a suggestion, so long as they are aren't included in the header file.
=> Refactors ISConstants.h::EPS to ISEarth.c::C_ECEF_EPS.

src/ISConstants.h, src/ISTcpClient.cpp, src/ISTcpClient.h, src/ISTcpServer.cpp, src/ISTcpServer.h, src/InertialSense.cpp, src/InertialSense.h
Refactor ISConstants.h::socket_t to is_socket_t to avoid conflict with external definition.
=> SN-6062: Refactor ISConstants.h::socket_t

python/supernpp/supernpp.py, scripts/build_all.py, scripts/build_manager.py, scripts/install_python_dependencies.sh, scripts/windows/build_tools.cmd, src/ISDataMappings.cpp, src/protocol_nmea.cpp, src/protocol_nmea.h, src/time_conversion.cpp, src/time_conversion.h, tests/CMakeLists.txt, tests/test_data_utils.cpp, tests/test_data_utils.h, tests/test_protocol_nmea.cpp, tests/test_time_conversion.cpp
- Fixed signedness of debug integer array (debug_array_t) in ISDataMappings.cpp.
- Added ZDA timestamp skip debug code.
- Added corrective offset for ZDA tmestamp skip.
- Fixed UtcDateTimeToGpsTime() leap second offset issue that caueded 1ms rounding error.
- Fixed rounding error in julianToDate() used in nmea_zda() output generation.
=> SN-6066 zda skips 1s

tests/runtime/device_runtime_tests.cpp, tests/runtime/device_runtime_tests.h
Add a runtime test for $INTEL, looking for anomalies in the timestamp and periodicity.
=> Add runtime test for NMEA $INTEL

src/ISDataMappings.cpp, src/data_sets.h
(IMX) Fixes a bug when IMX does not report GNSS1_INIT_FAULT reporting. (SN-6105)
(GPX) In DID_GPX_STATUS a field was added to report GNSS last reset reason. (SN-6105)
=> SN-6105: Fix IMX's GNSS1_INIT_FAULT reporting.

src/data_sets.h
-(GPX) (PR-1078) Add status bits to indicate recent Rx traffic on GPX serial ports. (SN-6141)
=> SN-6141: Add GPX_STATUS_x_RX_TRAFFIC_NOT_DECTECTED bits to GPX_STATUS.

python/inertialsense/logInspector/logInspectorInternal.py, python/inertialsense/logInspector/logPlotter.py, python/inertialsense/logs/include/log_reader.h, python/inertialsense/logs/src/log_reader.cpp, src/ISDevice.h, src/InertialSense.cpp, src/InertialSense.h, src/pybindMacros.h, tests/gtest_helpers.h, tests/test_ISFirmwareUpdate.cpp
InertialSense::releaseDevice() closes DeviceLogger associated with device.
Light rework to InertialSense::OpenSerialPorts() to use ISDevice.
Made InertialSense::registerDevice() and InertialSense::registerNewDevice() from private to public scope.
Added mutex guards to ISDevice classes which access ports.
Also adds PORT_MONITOR plots to LogInspectorInternal.
=> SN-6142 - Adds multi-threading support for GPX LDP runner

src/ISComm.c, src/ISDataMappings.cpp, src/ISDisplay.cpp, src/data_sets.h
- Rename `txOverflows` to `txDataDrops` in  port_monitor_set_t.
- Stage (commented out) changes for single write of packet to serial port in ISComm.c
=> SN-6201 uart dma critical fault

src/ISComm.c, src/ISComm.h, src/ISDisplay.cpp, src/data_sets.h, src/pybindMacros.h
- Fix raw gps data drop on GPX.
- Add general fault status mask to GPX so any error is easily identifiable.
=> SN-6129 fix raw gps data drop

src/data_sets.h
To fix the magnetometer redundant sample output, we reduced the default output data rate from 100Hz to 50Hz because we don't want that much data by default and then provided an additional option to increase the output data rate to 100Hz while adjusting the magnetometer bandwidth (BW) settings.
=> SN-6143 mag redundant samples

src/ISDisplay.cpp
Remove space before DID index in cltool output.
=> Remove extra space from before DID index

src/data_sets.h
Added option to disable magnetometer and barometer sensors, to provide an option to reduce data in our PPD logs as well as processor load from sensor traffic.
=> SN-6405 mag baro disable option

src/data_sets.h
Add DID_IMU3_RAW at slow rate when DID_PIMU is present to PPD logs for triple IMU analysis.  This increases the PPD log stream about 1.5%.
=> SN-6405 Added slow rate logging of DID_IMU3_RAW to PPD

src/data_sets.h
Remove CXD5610 from IO_CONFIG_GPS_TYPE because it is not an option.
=> Remove CXD5610 from IO_CONFIG_GPS_TYPE

cltool/src/cltool_main.cpp, src/InertialSense.cpp
Change Cltool and InertialSense class to only stop broadcasts on current port and not all ports, to not interrupt communications on other ports.
=> SN-6188 Cltool now only stops broadcasting on current port, not all ports

hw-libs/printf/printf.h
At some point printf.h was removed from the SDK. printf.c is still there. Building for embedded systems requires printf.h See ISConstants.h:114:
```
#elif PLATFORM_IS_EMBEDDED
#ifndef ARDUINO_SAMD_ZERO
#include "printf.h"		// Use embedded-safe SNPRINTF
#endif
#define SNPRINTF snprintf_
#define VSNPRINTF vsnprintf_
```
=> Restore printf.h

src/ISDataMappings.cpp, src/ISDataMappings.h
This fixes conversion from double to string precision error that prints over 12 decimal figures and obscures the real number.  This issue is in ISDataMappings.cpp and appears in the EvalTool and Cltool.
=> Fix display of ellipsoid altitude in ISDataMappings

python/supernpp/supernpp.py, scripts/build_manager.py
This fixes issues with running NPP tests from build_test_all script in windows.
=> Fix windows build_test_all.bat

ExampleProjects/InertialSense_log_reader_RegCmp/LogReader_RegCmp.cpp, cltool/src/cltool.cpp, scripts/windows/build_tools.cmd
- Automatically find the location for nmake used to build in Windows.  This change prevents the build process from breaking everytime Windows provides an updated version.
- Add includes for chrono and ctime in cltool and LogReader_RegCmp necessary for Windows build.
=> SN-6487 find nmake

src/ISDevice.cpp, src/util/util.cpp
Fix areas missed in develop for switching the dirty character in our version string from '*" to '^'.
=> Change dirty character from * to ^

src/DataCSV.cpp, src/ISDataMappings.cpp, src/ISDataMappings.h
This corrects an issue introduced in release 2.2.0 in which the CSV units for angles was converted to degrees and reduced precision.  The reverts to radians and provides full precision.
=> SN-6595 Do not convert units and reduce precision for CSV logs

src/ISComm.c
- (SDK) (SN-6599) Resolved issue where an edge case in is_comm_free() would cause ISComm buffer to fill up even when data in the buffer has been assessed.
=> SN-6599: ISComm reset empty buffer

src/data_sets.h
- (EvalTool) (SN-6630, PR- ) Fixed bug in evalTool where, in rare cases, DID_GPSx_SAT and DID_GPSx_SIG could get corrupted.
=> SN-6630: EvalEool sat/sig corruption

python/logInspector/logPlotter.py
LogInspector crashes because data does not exist in the log:
1 Delta Time (IMU3 data is not always in the log)
2  IMU3 Gyro Combined
3  IMU3 Accel Combined
4  RTK Obs Rover-Base Single Diff
5  GPS Velocity NED
=> Fixed bugs causing crash when there is no data in the log

ExampleProjects/Minimal_ISDevice/CMakeLists.txt, ExampleProjects/Minimal_ISDevice/ISDeviceExample1.cpp, src/DeviceFactory.h, src/ISComm.h, src/ISDevice.cpp, src/ISDevice.h, src/ISLogger.h, src/PortFactory.cpp, src/PortFactory.h, src/PortManager.cpp, src/core/base_port.h
The main purpose of this PR is to demonstrate the functionality of ISDevice and port_handle_t from the latest `develop` branch of the SDK, for basic discovery/comms to an Inertial Sense device.  ISDeviceExample1.cpp is heavily documented, and you are encouraged to read through it to understand how it operates.  This is as much a review of the code, as it is a review of the documentation for customers and usage of the SDK.
Also,
Adds default implementation for DeviceFactory::allocateDevice()
Misc cleanup/improvements in ISDevice::validate()
Fixed bug where ISDevice::constructors would not initialize/copy sysParams. Added argument to ISDevice::connect() to allow performing validation() on connect (or not, by default). Rearranged PortFactory::bindPort() and PortFactory::validatePort() …
=> Example Project for ISDevice and port_handle_t

src/data_sets.h
- (SDK, IMX) (SN-6720) Added ability to select primary source for NMEA GNSS output via DID_SYS_PARAMS.sysStatus.SYS_STATUS_PRIMARY_NMEA_GNSS_SOURCE (where 0 is GNSS1, 1 is GNSS2).
=> SN-6720: NMEA source selection added defines

cltool/CMakeLists.txt, cltool/src/cltool.cpp, cltool/src/cltool.h, cltool/src/cltool_main.cpp, src/ISComm.h, src/ISDataMappings.cpp, src/ISDataMappings.h, src/ISDisplay.cpp, src/ISDisplay.h, src/InertialSense.cpp, src/InertialSense.h, src/com_manager.c, tests/CMakeLists.txt, tests/test_ISDataMappings.cpp
- Created cltool options -get and -set which can read or write to any DID using single line yaml format.
- Fixed ISDataMapping representation of arrays within data sets.
This PR is for the revised version of the cltool -get and -set options to read/write to any DID.  This took way longer than it should have.  It uses single line YAML input which is clean enough.  Unfortunately it does require quotes for the entire section, but this is necessary to prevent parsing errors on some platforms.  [@Kyle Mallory](https://inertialsensegroup.slack.com/team/U03DDVBFKT5) I didn't implement automatic format detection for lack of time (we can consider that later).  The out YAML is compact enough (and I've run out of time) that I don't care to implement a feature for selecting different output formats. …
=> SN-6835 cltool -get -set yaml

cltool/src/cltool_main.cpp, src/ISDataMappings.cpp, tests/test_ISDataMappings.cpp
Fixed invalid message "Failed to setup communications!" in cltool when using -sysCmd.  Recent refactor to return error to the command line broke this.  The sysCmd as well setting the platformType would send correctly but cause this error to be reported.
=> SN-6866 cltool syscmd error

CMakeLists.txt, src/InertialSense.cpp, src/InertialSense.h
- Fix NPP build in Windows due to statically linked yaml-cpp.
- Pull forward IMX/GPX flash sync improvements from develop.
=> Flash cfg sync cleanup

src/ISFirmwareUpdater.cpp
Specifically, the message clearly indicated success or failure, and directs the user to inspect the logs for specific error messages.
Note that Firmware Updates are complex mechanisms, particularly with packages, and that some upgrades may fail while others succeed.  It is important not to blindly communicate that the process was a pass or fail outcome, and instead direct the user to investigate the outcomes of each individual step.
=> SN-6893 - Fixes/improves the completion message when a firmware update finishes, but has errors.

src/ISmDnsPortFactory.cpp, src/util/uri.hpp
This fixes c++17 issues so that we can avoid pushing compiler issues onto our customers.
=> Fix build errors and warnings for C++17

src/ISBootloaderThread.cpp
Fixes an issue where IMX bootloader updates fail when starting with bootloader v6g and updating multiple devices. The fix adds a delay in the SDK firmware updater to ensure devices enter ROM bootloader mode before the update proceeds.
=> SN-7018 bootloader v6g fail w two imxs

src/ISEarth.c, src/ISPose.c
Faster euler-to-quaternion for ECEF-to-NED by skipping sin, cos and multiplications for zero
=> faster ecef-to-ned computation
