- EVB-2/IS_EVB-2/src/communications.cpp
- src/ISDisplay.cpp
- src/ISDisplay.h
- src/cltool.cpp
- src/cltool_main.cpp
Add support for throttle scalar.  Fix nonblockingkeyboard bug in ISDisplay which prevented keyboard inputs in Luna.
> Luna 1215 add throttle scalar

- src/ISEarth.c
- src/ISEarth.h
added a function for computing range bearing from two given geodetic coordinates
> add range bearing computation to ISEarth

- EVB-2/IS_EVB-2/src/drivers/d_quadEnc.c
- EVB-2/Makefile
- cltool/VS_project/cltool.vcxproj.user
- src/ISDataMappings.cpp
- src/luna_data_sets.h
This changes the wheel control pwm to high resolution, 10K counts for the the duty cycle.
> LUNA-1398 zt mower engine kill at first waypoint

- src/luna_data_sets.h
Remove references to coyote in EVB code.
> Coyote cleanup

- src/ISFileManager.cpp
- src/ISFileManager.h
> Sn 486 build path

- src/ISDisplay.cpp
- src/ISDisplay.h
- src/ISFileManager.cpp
- src/cltool.cpp
- src/cltool.h
- src/cltool_main.cpp
This will allow the cInertialSenseDisplay destructor to work.
> Revert g_inertialSenseDisplay from pointer to static member

- src/data_sets.h
Move GPS velocity validation check into GPS_ublox.cpp so that existing golden logs process properly.
> Move GPS validation into GPS library

- EVB-2/IS_EVB-2/IS_EVB-2.cppproj
- EVB-2/IS_EVB-2/src/globals.c
Fixed issue where strcmp and strch don't work in windows gcc arm compiler
> Fixed evb2 build time and date in version string

- EVB-2/IS_EVB-2/src/globals.c
- EVB-2/IS_EVB-2/src/globals.h
Reuse EVB version date time code.  Ask and ye shall receive, Steve.
> Move code to shared location

- src/ISMatrix.h
Found a potentially unsafe division
> SN-986 Fixed unsafe division

- EVB-2/IS_EVB-2/IS_EVB-2.cppproj
- EVB-2/IS_EVB-2/src/communications.cpp
- cltool/VS_project/cltool.vcxproj
- cltool/VS_project/cltool.vcxproj.user
- src/ISDisplay.cpp
- src/ISDisplay.h
- src/cltool_main.cpp
This changes the cltool so that it will refresh the display regardless whether data is received or not, allowing the -edit command to be used with DIDs that are write/send only and don't respond (e.g. DID_EVB_LUNA_AUX_COMMAND).
> Add luna aux command

- src/data_sets.h
Move GPS init fault flag to general fault code along side other sensor fault flags.
> SN-816 Move error bit to general fault code along with other sensor fault bits

- src/data_sets.h
Add detail to RMC preset comments.
> SN-1160 rmc usability

- cltool/VS_project/cltool.vcxproj
- cltool/VS_project/cltool.vcxproj.filters
- hw-libs/misc/bootloaderShared.h
- src/data_sets.h
- src/inertialSenseBootLoader.c
> Release 1.8.6.b

- src/data_sets.h
> SN-1466 Pass GPS into testbed via serial connection

- src/ISDataMappings.cpp
- src/luna_data_sets.h
Add first order turnrate feedforward.
> LUNA-2304 hoverbot world lawn fix

- src/ISDataMappings.cpp
- src/luna_data_sets.h
* Created first order turnrate feedforward
* Added wheel feedback control gain deadband for ZTM
> LUNA-2304 hoverbot world lawn fix (#235)

- python/logInspector/logInspectorInternal.py
- python/logInspector/logPlotter.py
- python/pylib/data_sets.py
- src/ISDataMappings.cpp
- src/data_sets.c
- src/data_sets.h
- src/pybindMacros.h
Move reference IMU inside nav class.
> SN-1747 add reference to scomp

- EVB-2/IS_EVB-2/src/globals.c
- hw-libs/drivers/d_flash.c
- Move flash write count and failure outside of d_flash.c
> SN-1885 Fix auto flash write after mag recal

- src/data_sets.h
Make sensor config bitmasks easer to read and manage.
> Sensor bitmask shift

- python/logInspector/include/log_reader.h
- python/logInspector/src/log_reader.cpp
- python/pylib/ISToolsDataSorted.py
- python/pylib/ISToolsPlot.py
- python/pylib/data_sets.py
- src/ISDataMappings.cpp
- src/data_sets.c
- src/data_sets.h
- src/test/test_com_manager_2.cpp
This will make merge from development cleaner.
> Rename DID_SENSORS_IS1 and DID_SENSORS_IS2 to DID_SENSORS_RAW and DID_SENSORS_TCAL

- src/data_sets.c
- src/data_sets.h
- src/protocol_nmea.cpp
- src/protocol_nmea.h
Part of RTOS sample task optimization.  Also addressed compiler warnings.
> SN-2028 More sample task optimization

- EVB-2/IS_EVB-2/src/globals.h
- src/ISDataMappings.cpp
- src/data_sets.c
- src/data_sets.h
- src/protocol_nmea.cpp
- src/protocol_nmea.h
Ensure we aren't running RTOS profiling during a flash write.
> SN-2225 rtos runtime error

- hw-libs/misc/maintenance.c
- python/logInspector/include/log_reader.h
- python/logInspector/logPlotter.py
- python/logInspector/src/log_reader.cpp
- python/pylib/ISToolsDataSorted.py
- python/pylib/ISToolsPlot.py
- python/pylib/data_sets.py
- src/ISDataMappings.cpp
- src/data_sets.c
- src/data_sets.h
- src/pybindMacros.h
- src/test/test_com_manager_2.cpp
Consolidate data structures so that we have consistent data types for uncalibrated, temp calibrated, and temp + motion calibrated data.  Use this consistent data type for DID_SCOMP LPF averaging which allows us to average sensor data over long periods of time.
> SN-561 evaluate g sensitivity

- src/ISDataMappings.cpp
Fix definition for imu3_t in ISDataMappings.cpp so that conversion to CSV works.
> SN-2319 new imu dids dont convert to csv

- python/logInspector/logInspector.py
- python/logInspector/logReader.py
Replace our "Reference INS" Serial Number with title.
INL2 encoding failing for window Name bar. Commented it out unless you have a suggestion or feel it is needed.
> Sn 2304 log using Reference INS

- python/logInspector/logInspector.py
- python/pylib/ISToolsDataSorted.py
- src/ISDataMappings.cpp
- src/data_sets.h
- src/pybindMacros.h
Created Platform and RTK Preset by combining carrier board and GPS Preset
> SN-2324 RUG-3 evaltool config

- python/logInspector/logReader.py
- src/DeviceLog.h
- src/ISConstants.h
- src/ISLogger.cpp
- src/ISLogger.h
Adjusts RMS thresholds for IMX-5 and Reference SPAN INS.
> SN-2520 relax rms thresholds for IMX-5

- src/ISBootloaderBase.cpp
This code wasn't being used and isn't important, so I took it out
> SN-2428 Remove unused and unreachable code

- src/ISBootloaderAPP.cpp
- src/ISBootloaderDFU.cpp
- src/ISBootloaderISB.cpp
- src/ISBootloaderSAMBA.cpp
- src/ISBootloaderThread.cpp
Ensure bootloader version is always printed.  Reduce bootloader wording.
> SN-2695 bootloader version not read from file

- src/data_sets.h
> Sn 2121 startrack

- src/ISDataMappings.cpp
- src/data_sets.h
Allow strobe input to trigger on both rising and falling edges.  Adds direction of strobe to strobe message.
> SN-2699 modify strobe input

- src/ISBootloaderAPP.cpp
- src/ISBootloaderBase.cpp
- src/ISBootloaderBase.h
- src/ISBootloaderISB.cpp
- src/ISBootloaderSAMBA.cpp
- src/ISBootloaderThread.cpp
- src/InertialSense.cpp
- src/serialPortPlatform.c
- Put device into 115200 baud mode when using SAM-BA first-stage bootloader
- Fix SAM-BA upload over UART (was using wrong buffer)
- Clean up formatting
> SN-2708 UART-based SAM-BA firmware update fixes

- ros/README.md
- ros/include/inertial_sense_ros.h
- ros/launch/test_params.yaml
- ros/src/inertial_sense_ros.cpp
Get param names to match topic names names.  Converted rs_param_t to ParamHelper class.
> SN-2679 Created c++ class for param helper

- src/ISBootloaderBase.cpp
- src/ISBootloaderThread.cpp
- src/ISClient.cpp
- src/ISDisplay.cpp
- src/ISDisplay.h
- src/InertialSense.cpp
- src/InertialSense.h
- src/cltool_main.cpp
- src/ihex.c
Cherry pick ci-hdw into development excluding ros SDK refactor.
> Cherry pick ci-hdw

- src/ISDataMappings.cpp
- src/data_sets.h
- src/protocol_nmea.cpp
- src/pybindMacros.h
Multi-frequency satellite info support.
> SN-2944 gpx protocol support

- ExampleProjects/Bootloader/VS_Project/ISBootloaderExample.vcxproj
- ExampleProjects/Bootloader/VS_Project/ISBootloaderExample.vcxproj.filters
- ExampleProjects/Logger/VS_Project/ISLoggerExample.vcxproj
- ExampleProjects/Logger/VS_Project/ISLoggerExample.vcxproj.filters
- cltool/VS_project/cltool.vcxproj
- cltool/VS_project/cltool.vcxproj.filters
- python/logInspector/logInspector.py
- python/logInspector/logInspectorInternal.py
- python/logInspector/logPlotter.py
- src/ISEarth.c
Fix gndSpeedToVelEcef() backwards rotation in ISEarth.c.  Added GPS velocity and GPS position to LogInspector.  Refactored LogInspector plot selection to list view to make it easier to find plots.
> Release 2.0.0 fix gnd speed to vel ecef

- python/logInspector/logInspector.py
- python/logInspector/logInspectorInternal.py
- python/logInspector/logPlotter.py
This adds a Save All Plots button to the LogInspector to automatically save all plots to file.
> SN-3000 loginspector batch plot save

- EVB-2/IS_EVB-2/src/evb_tasks.cpp
- EVB-2/IS_EVB-2/src/misc/init.c
- hw-libs/drivers/SAMx70/d_serial.c
- hw-libs/drivers/SAMx70/d_serial.h
- src/com_manager.h
Add TX buffer limit status to serial driver. Remove overrun pointer from serInit().
> Sn 3024 add imx5 serial tx buffer limit indication

- src/data_sets.h
This goes with [ ](https://github.com/inertialsense/imx/pull/502)
> SN-2895 EVB3 to reserved

- src/cltool.cpp
- src/cltool.h
- src/cltool_main.cpp
- src/data_sets.h
Added -sysCmd=[c] option to cltool.
> Add sys cmd to cltool

- CMakeLists.txt
- cltool/CMakeLists.txt
- scripts/install_yaml-cpp.bat
- src/InertialSense.cpp
Fixes to YAML functions in SDK. Batch script to install yaml-cpp in Windows. Put back the apt install of yaml-cpp
> SN-3334 yaml-cpp SDK test

- src/ISConstants.h
- src/data_sets.h
- src/protocol_nmea.cpp
- src/protocol_nmea.h
- src/pybindMacros.h
- src/test/CMakeLists.txt
- src/test/test_nmea.cpp
Create SDK unit tests for NMEA to binary and binary to NMEA functions found in protocol_nmea.cpp.  Added missing conversion functions for NMEA GGA, GLL, GSA and $INFO to support proper unit tests and ci-hdw tests.
> SN-3382 nmea gps not streaming

- src/data_sets.h
Created GPS1 to Serial0 Bridge for Lambda Board NMEA tests
> Added GPS1 to Serial0 Bridge

- src/cltool.cpp
- src/cltool_main.cpp
Exit cltool tool when sending sysCmd.
> Always exit the program if the user supplies a sysCmd

- CMakeCommon.txt
- src/ISBootloaderAPP.cpp
- src/ISBootloaderBase.cpp
- src/ISBootloaderDFU.cpp
- src/ISBootloaderISB.cpp
- src/ISBootloaderSAMBA.cpp
- src/ISBootloaderThread.cpp
- src/ISEarth.c
- src/ISMatrix.h
- src/InertialSense.cpp
- src/cltool_main.cpp
- src/message_stats.cpp
Restore ISB bootloader support in cltool.
> SN-3875 Cherry pick cltool ISB firmware update support

- src/ISEarth.c
- src/data_sets.h
Add sys command for serial bridge for current port.  This will allow for bridging ser1 to ser0 on the IMX-5.
> Add sys commands for serial bridge for current port

- src/protocol_nmea.cpp
Fix broadcast of nmea gsv message.
> SN-3893 nmea gxgsv not streaming

- src/ISConstants.h
- src/data_sets.c
- src/data_sets.h
- src/protocol_nmea.cpp
- src/protocol_nmea.h
Fix streaming of NMEA $GNVTG and $GNRMC message.  Add $INTEL message.
> SN-3868 pre enable gnvtg gnrmc

- src/ISBootloaderAPP.cpp
- src/ISBootloaderBase.cpp
Fixes issue in https://inertialsense.atlassian.net/browse/SN-3756. Able to start updating regardless of streaming speed. 330Kb/s tested.
> Sn 3756 update durring ppd

- src/protocol_nmea.cpp
> Break for invalid pointer

- EVB-2/IS_EVB-2/src/communications.cpp
- EVB-2/IS_EVB-2/src/globals.c
- EVB-2/IS_EVB-2/src/globals.h
- hw-libs/printf/printf.h
- src/ISConstants.h
- src/ISEarth.c
Revises llaDegValid() and rename evb config functions for clarity.
> Revise llaDegValid().  Rename reset_evb_flash_cfg_defaults()

- src/ISBootloaderISB.cpp
- src/ISBootloaderThread.cpp
added try catch around fault point Fortem was reporting so app cancels update and avoids crash
> Sn 4069 graceful handling of fault

- src/ISSerialPort.cpp
Include filters for other possible port names. This may need expanded for other platforms.
> Include filters for other possible port names

- src/ISSerialPort.cpp
Reverts inertialsense/inertial-sense-sdk#462
> Revert "Remove problematic port names"

- src/ISSerialPort.cpp
* Revert "Remove problematic port names (#462)"
This reverts commit 9259c2ef284b9275a91dac4ff4884021cd401a13.
* Update ISSerialPort.cpp
* Update ISSerialPort.cpp
* Update ISSerialPort.cpp
---------
> Revert "Remove problematic port names" (#463)

- src/com_manager.c
Prevent use of null pointer in initComManager()
> Fix null pointer access

- src/ISComm.c
- src/ISComm.h
- src/com_manager.c
- src/com_manager.h
- src/test/test_ISComm.cpp
Add packet parse timeout to ISComm.cpp.
> SN-4293 Created is_comm_parse_timeout

- src/ISFirmwareUpdater.cpp
- src/ISFirmwareUpdater.h
- src/InertialSense.cpp
General EvalTool GPX update polish items.
> General EvalTool GPX update polish items.

- src/data_sets.h
IMX will reenable GPX messages when a init state is active
> Sn 4400 gpx reenable messages

- src/ISComm.h
- src/protocol_nmea.cpp
- src/protocol_nmea.h
Added helpful NMEA command generator to EvalTool to facilitate sending NMEA commands to the IMX.
> Added NMEA command generator to EvalTool

- src/ISDisplay.h
- src/cltool.cpp
- src/cltool_main.cpp
Run cltool in quiet mode by default to make it more command line friendly.
> Run cltool in quiet mode by default

- src/protocol_nmea.h
IMX now populates DID_GPSx_VERSION with GPX versions as swVersion and hwVersion.
> Sn 4316 gp sv includes gpx info

- src/ISComm.h
- src/com_manager.c
Fixed parameter order in comManagerSend() and added some comments.
> Fix comManagerSend() parameter order and add comments

- src/data_sets.h
- src/protocol_nmea.cpp
- src/protocol_nmea.h
- src/test/test_protocol_nmea.cpp
(SDK) Separated the NMEA period multiple from the ISB RMC period multiple.
> Sn 4572 backport nmea period separation

- .clang-format
- .github/workflows/cpp-linter.yml
- .github/workflows/main.yml
- scripts/build_test_cmake.sh
- scripts/install_gtest.sh
- scripts/lib/echo_color.sh
- scripts/lib/results_build.sh
- scripts/lib/results_tests.sh
- scripts/lib/update_build_info.sh
- scripts/lib/update_repo_info.sh
- src/InertialSense.cpp
- src/cltool.cpp
- src/serialPort.h
- src/serialPortPlatform.c
- src/test/test_com_manager_2.cpp
This has a few fixes, and moves to a cloud-based runner (for a few reasons, but mostly because we don't care about hardware, so why not).  It also adds a workflow to do c++ linting.  Its not a requirement, but probably something we should start exploring more.
> Sdk GitHub actions

- src/ISBootloaderAPP.cpp
- src/data_sets.c
- src/data_sets.h
- src/protocol_nmea.cpp
This fixes ability to update IMX-5 firmware from release r1.10.x and before.
> SN-4644 fix IMX 1x firmware update development

- EVB-2/IS_EVB-2/IS_EVB-2.cppproj
- EVB-2/IS_EVB-2/src/communications.cpp
- hw-libs/bootloader/bootloaderApp.c
- hw-libs/bootloader/bootloaderApp.h
- src/data_sets.h
- src/protocol_nmea.cpp
This converts the chip erase pin to a boot mode pin.
> SN-4336 convert chip erase to boot mode pin

- src/data_sets.h
Create sys command that enables serial bridge on IMX to GPX and loopback on GPX.
> Add loopback to gpx

- src/data_sets.h
- src/protocol_nmea.cpp
- src/protocol_nmea.h
- src/pybindMacros.h
- src/test/test_protocol_nmea.cpp
- (SDK) DID_NMEA_BCAST_PERIOD matches the ASCII message $ASCE instead of the deprecated $ASCB.
> DEVELOPMENT NMEA asce update

- ExampleProjects/Ascii/ISAsciiExample.c
- ExampleProjects/Ascii/README.md
- src/data_sets.h
- src/protocol_nmea.cpp
- src/protocol_nmea.h
- tests/test_ISComm.cpp
- tests/test_com_manager.cpp
> Sn 4606 nmea did update2

- src/protocol_nmea.cpp
- src/protocol_nmea.h
- (SDK) Added support for $ASCE requests in the NMEA protocol.
> Sn 4817 impliment asce query

- src/ISConstants.h
- src/ISEarth.c
Equatorial ECEF points are converted to North pole latitude.
> ecef2lla() bug fix

- src/DeviceLog.h
- src/ISLogger.cpp
- src/ISLogger.h
- (SDK) Added support to ISLogger for filenames with only index number in filename.
> SN-4892 is logger filename

- python/logInspector/logPlotter.py
- src/ISFirmwareUpdater.cpp
- src/data_sets.h
- (SDK) Fixed incorrect MD5 digest selection when updating pre-release GPX firmware.
> SN-4946 gpx firmware update issues

- src/util/md5.h
- (IMX) DID_RMC request not send proper information.
> fix windows compiler error

- src/ISFileManager.cpp
- src/ISFileManager.h
Add convenience function CurrentWorkingDirectory() that returns std::string.
> Provide a convenience function CurrentWorkingDirectory()

- python/logInspector/logInspector.py
- python/logInspector/logInspectorInternal.py
- python/logInspector/logPlotter.py
This PR adds new LogInspector features:
- Hide/show side panel button (to give more room for plotting).
- `Window` button to spawn new LogInspector instance pointing to same data log directory.
- Climb rate plots.
> Log inspector hide panel

- src/util/util.cpp
- src/util/util.h
This PR just implements a utility function to handle printf-style formatting to a std::string().
> More Test Fixture

- src/data_sets.h
Fixes error in sony state-machine causing race condition.
> added fault flag

- python/supernpp/supernpp.py
- src/ISLogger.cpp
Added .raw log processing to enable running NPP from logInspector
> ISLogger and SuperNPP updates

- src/protocol_nmea.cpp
NMEA GSV sentence exludes sats < 0 elevation.
NMEA GGA 'fixQuality' reinforced to reduce likelihood of errant values.
> NMEA GSV sentence now uses i32 for Ele/Azi values.

- src/DeviceLogRaw.cpp
- src/ISComm.c
- src/ISDataMappings.cpp
- src/data_sets.h
- (GPX) Ephemeris broadcasting causes Tx overflow fixed.
- (IMX) Added general fault code to IMX's paired with GPX to alert the user if the GPX had Tx limited or Rx overrun events occur.
> Sn 5061 stagger ephm

- tests/CMakeLists.txt
- tests/runtime/device_runtime_tests.cpp
- tests/runtime/device_runtime_tests.h
Add more helpful debug info to runtime tests output.
> Add more info to runtime tests output

- src/ISBootloaderAPP.cpp
- src/ISDFUFirmwareUpdater.cpp
- src/ISDataMappings.cpp
- src/ISDisplay.cpp
- src/ISFirmwareUpdater.cpp
- src/data_sets.c
- src/data_sets.h
- src/protocol/FirmwareUpdate.cpp
- src/protocol/FirmwareUpdate.h
- src/protocol_nmea.cpp
Add hardware detection check to BIT basic test to ensure correct firmware is loaded and used.
> SN-4452 evaltool set otp manf info

- .github/workflows/main.yml
- CMakeLists.txt
- ExampleProjects/Arduino/ReadIS/ReadIS.ino
- ros/CMakeLists.txt
- ros/include/inertial_sense_ros.h
- ros/src/inertial_sense_ros.cpp
- tests/runtime/device_runtime_tests.cpp
- tests/runtime/device_runtime_tests.h
- tests/test_data_utils.cpp
- tests/test_runtime_tests.cpp
We haven't built ROS using the release 2.x changes.  This fixes related issues.
> Fix r2 build errors

- src/data_sets.h
(GPX) Added GNSS firmware update required detection.
> Adds fault definition

- src/protocol_nmea.cpp
Switch $INTEL message timestamp from milliseconds to seconds per request.
> Display $INTEL time in seconds

- cltool/src/cltool.cpp
- cltool/src/cltool.h
- cltool/src/cltool_main.cpp
Close cltool following sending the reset command when using the -reset option.
> Close cltool after reset

- ros/src/inertial_sense_ros.cpp
- ros/test/test_basic_unit_tests.cpp
Use the InertialSense class flash config sync functions for reading and setting the flash config in our ROS node.
> SN-5230 ros flash config sync

- src/serialPortPlatform.c
Fixes serial write issue in serialPortPlatform.c that drops data by waiting on OS to accept input data.  Clean up code and comments.
> SN-5281 sdk serial write failure

- cltool/src/cltool_main.cpp
- src/InertialSense.cpp
- src/InertialSense.h
Add the ability to set COM port for SetEventFilter(). This was requested in the case that multiple ports are connected currently.
> add ability so set COM port for SetEventFilter()

- src/ISComm.c
- src/InertialSense.cpp
Remove debug code from ISComm and InertialSense class used to debug serialPortWritePlatform() bug.
> SN-5281 Remove debug code

- src/data_sets.h
> SN-4980 Remove unused status mag recal status flag

- ExampleProjects/ISLoggerSimple/ISLoggerSimpleExample.cpp
Fixes a broken logger in the ISLoggerSimpleExample.cpp project.
> fix/SN-5425 ISLoggerSimpleExample won't log

- python/logInspector/logInspector.py
- python/logInspector/logInspectorInternal.py
- python/logInspector/logPlotter.py
- python/pylib/ISToolsDataSorted.py
Fixed these issues
1. Downsample can be zero and cause a crash
2. Initial zeros in the sensor data
3. Time jump in the system time due to time of week offset update when GNSS becomes available
4. Absence of sensor data in the log causes a crash when plotting
> Log inspector issue fixes

- python/logInspector/logInspector.py
- python/logInspector/logInspectorInternal.py
- python/logInspector/logPlotter.py
- python/pylib/ISToolsDataSorted.py
- python/supernpp/supernpp.py
The same as pull request for develop, fixing issues in logInspector for develop 1.12
1.  Downsample can be zero and cause a crash
2.  Initial zeros in the sensor data
3.  Time jump in the system time due to time of week offset update when GNSS becomes available
4.  Absence of sensor data in the log causes a crash when plotting
> Log inspector issues for develop 1.12

- cltool/src/cltool.cpp
- cltool/src/cltool.h
- cltool/src/cltool_main.cpp
- src/ISDataMappings.cpp
- src/ISDisplay.cpp
- src/data_sets.h
- src/pybindMacros.h
Added event parsing to CLTool
Added additional RTK ephemeris debugging.
> Added event parsing to CLTool

- src/data_sets.h
- (SDK) Added Ephemeris receive bit to DID_GPS_SAT.
> Sn 5511 ephdebugging

- python/logInspector/logInspectorInternal.py
- python/logInspector/logPlotter.py
- src/data_sets.h
add plots for ephem to log inspector
> Sn 4985 ephemeris time

- src/data_sets.h
- src/protocol_nmea.cpp
- (SDK) GxGSV SDK documentation update.
> update gvs docs

- src/ISBootloaderISB.cpp
- src/ISBootloaderISB.h
- src/ISBootloaderThread.cpp
- src/InertialSense.cpp
Add "handshake" status to IMX firmware update output status.  Rename sync() to handshake_sync() for clarity.
> SN-5457 add handshake response

- src/rtk_defines.h
- tests/test_ISComm.cpp
- tests/test_com_manager.cpp
> Sn 5492 merge f9 p work into dev

- .github/workflows/main.yml
- ros/include/inertial_sense_ros.h
- ros/test/test_basic_unit_tests.cpp
> Sn 4103 - Enable ROS unit tests and bridge test.

- cltool/src/cltool.cpp
- cltool/src/cltool.h
- cltool/src/cltool_main.cpp
- src/InertialSense.cpp
- src/InertialSense.h
- Fixes cltool -sysCmd send reliability issue
- Adds disable device verification option -vd.
> Add option to cltool to disable device verification

- cltool/CMakeLists.txt
- cltool/src/cltool.cpp
- src/ISDataMappings.cpp
- src/ISDataMappings.h
- src/ISDisplay.cpp
- src/ISDisplay.h
- Fix cltool high data rate streaming of non-rmc messages by adding and using cISDataMappings::DefaultPeriodMultiple().
- Fix ISDisplay print of data sets that have a formatted output to not use the generic ISDataMapping output.
> SN-5600 cltool bugs

- src/ISDataMappings.cpp
- src/ISDisplay.cpp
- src/data_sets.h
- (GPX) DID_GPX_STATUS message now contains more information about GNSS receiver state.
> change GPX_STATUS def

- src/ISLogger.cpp
Replace std::mutex with our own mutex as a work around to prevent Log Inspector crash on Jake's Windows machine.
> Replace std::mutex with homebrew to prevent Windows crash

- .github/workflows/main.yml
- cltool/src/cltool.cpp
- cltool/src/cltool.h
- cltool/src/cltool_main.cpp
- src/ISDisplay.cpp
- Add `-durMs` option for millisecond resolution timeout.
- Fixed typos in ISDisplay pretty output.
> SN-5612 cltool CI-hdw support

- cltool/src/cltool.cpp
- src/ISComm.c
- src/ISComm.h
- src/InertialSense.cpp
- src/InertialSense.h
- src/data_sets.h
- src/serialPortPlatform.c
Add sys command to re-initialize ser0.
> re-init Ser0 support

- src/com_manager.c
- (IMX) IMX paired with GPX now responds to requests for DID_RTK_DEBUG.
> RTK debug now turns on when requested

- src/data_sets.h
- src/protocol_nmea.cpp
- src/protocol_nmea.h
(IMX) Added support for save persistent of the GSV filter.
> save gsv filter

- src/protocol_nmea.cpp
- src/protocol_nmea.h
(SDK) $STPB message now clears the GSV filter.
(SDK) GxGSV message with a period of 0 targeting all ports now clears the GSV filter.
> Sn 5675 stpb clears filter

- src/data_sets.h
Ability to send hardware non-UART based software reset and stop broadcast commands on Ser0 for debug.
> SN-5749 bit bang nmea stpb

- python/logInspector/logPlotter.py
> Altitude plot crash fix

- src/data_sets.h
Default broadcast messages out work for debug work
Added sysCmd 69,70 to toggle Tx0 pin state
> Sn 5834 Default broadcast messages out work for debug work

- ROS/ros1/src/inertial_sense_ros.cpp
- python/supernpp/supernpp.py
- Update islogger use in inertial_sense_ros.
- Clean up directory paths in supernpp.
> Sn 5842 imx unit tests windows gtest

- cltool/src/cltool.cpp
- src/DataCSV.cpp
- src/DataJSON.cpp
- src/ISDataMappings.cpp
- src/ISDataMappings.h
- src/ISDisplay.cpp
- tests/test_ISDataMappings.cpp
Rename the following for clarity.
NameToInfo() -> NameToInfoMap()
IndexToInfo() -> IndexToInfoMap()
> Rename IndexToInfo() and NameToinfo()

- src/data_sets.h
Add support for STIM320 reference IMU.
> Reference IMU working

- CMakeLists.txt
- python/logInspector/setup.py
- src/ISFileManager.cpp
Is logger implementation in Windows was not compiling. attempt 2
> Sn 5869 is logger windows fix. attempt 2. Lets try this again

- python/logInspector/logPlotter.py
Add plot for dead reckoning in INS Status plots of Log Inspector
> Plot dead reckoning

- python/supernpp/supernpp.py
- scripts/windows/build_is_sdk.bat
> Supernpp fix

- src/ISMatrix.c
- src/ISMatrix.h
- src/ISPose.c
- src/filters.cpp
- src/protocol_nmea.cpp
- tests/test_math.cpp
The reverts conversion of inline macros to function calls and then applies specific function calls where performance is not needed so that we can reduce instruction space usage.
> SN-5899 imx mcu optimizations

- .gitignore
- python/supernpp/supernpp.py
- scripts/build_log_inspector.sh
- scripts/install_gtest.sh
- scripts/install_sdk_dependencies.sh
- scripts/windows/build_log_inspector.bat
- scripts/windows/build_run_log_inspector.bat
- scripts/windows/clean_all.bat
- scripts/windows/clean_log_inspector.bat
- scripts/windows/clean_python_cache.bat
- scripts/windows/install_log_inspector_dependencies.bat
- src/ISLogger.cpp
- src/ISLogger.h
Fix the build_test_npp script in Windows so that RMS results awlays run and get displayed.
Use ONE python script for build_test_npp.py that runs in both Windows and Linux.
> SN-5924 fix windows scripts

- scripts/build_manager.py
> Fix firmware build scripts

- src/ISComm.c
> white space fix

- src/ISComm.c
- src/ISComm.h
Fix disable ser bridge mode on IMX
> SN-6005: Serial port bridge on IMX not working

- python/logInspector/logInspector.py
- python/logInspector/logInspectorInternal.py
- python/logInspector/logPlotter.py
- python/pylib/ISTools.py
- python/pylib/ISToolsData.py
- python/pylib/ISToolsDataSorted.py
- python/pylib/ISToolsGNSS.py
- python/pylib/ISToolsPlot.py
- python/pylib/newISDataAnalytics.py
Fix several items in LogInspector.  Add UTC time display instead of GPS time of week.
> Log inspector add utc time

- scripts/build_all.py
- scripts/build_manager.py
- scripts/install_python_dependencies.sh
Fixes issue where build_all.py did not return an error code
> Build all py return error code

- src/com_manager.cpp
- src/data_sets.h
- src/protocol_nmea.cpp
SN-6073: GRMC Serial Port Refactor alignment.
> SN-6073: GRMC Serial Port Refactor alignment

- python/logInspector/logInspectorInternal.py
- python/logInspector/logPlotter.py
- src/ISDataMappings.cpp
- src/data_sets.h
- Improved sys fault documentation in data_sets.h. 
- Fix python plots
> Improved sys fault documentation in data_sets.h.  Fix python plots

- src/data_sets.h
- (GPX) (PR-1074) DID_GPX_STATUS now reports recent Rx traffic in status bits.
- (IMX) (PR-1074) IMX now pings in GPX regularly.
> Sn 6110 gpx traffic detect v2 2 2

- cltool/src/cltool.cpp
- cltool/src/cltool.h
- cltool/src/cltool_main.cpp
* inital
* working better with 2.3
---------
> SN-6192 cltool evm (#816)

- cltool/src/cltool.cpp
- src/ISDisplay.cpp
- src/ISDisplay.h
- src/data_sets.h
Addes pretty print to cltool for memory Event messages.
> Sn 6219 evmi pretty print

- src/data_sets.h
Added velocity constraint parameter
> RTK EKF refactor

- ExampleProjects/Arduino/ReadIS/ImportSdkFiles.bat
- ExampleProjects/Arduino/ReadIS/ImportSdkFiles.sh
- ExampleProjects/Arduino/ReadIS/ReadIS.ino
- hw-libs/printf/printf.h
- src/ISConstants.h
Fix script to create and copy necessary files.
> SN-6133 Arduino Script

- src/ISDataMappings.cpp
- src/data_sets.h
Add brownout reset voltage threshold configuration to IMX and GPX
> Added BOR threshold config to IMX and GPX flash config

- python/logInspector/logPlotter.py
> Added satellite SNR plots

- src/ISDisplay.cpp
- src/data_sets.h
Replace HDW_STATUS_GPS_SATELLITE_RX with HDW_STATUS_GPS_SATELLITE_RX_VALID to increase bit meaning clarity.
> SN-6088 - Rename HDW_STATUS_GPS_SATELLITE_RX

- src/ISComm.c
- src/ISComm.h
- src/data_sets.h
Consolidate Changes for 2.4 release
> SN-6428: consolidate changes 2.4

- python/logInspector/logInspector.py
- python/logInspector/logInspectorInternal.py
- python/logInspector/logPlotter.py
- python/logInspector/logReader.py
- python/pylib/data_sets.py
- python/supernpp/supernpp.py
This PR introduces new unit tests for GPX RTK functionality and updates performance reporting and log processing in the SuperNPP and LogInspector modules. Key changes include:
- Refactoring SuperNPP initialization to load configuration from a YAML parameters file and updating log file discovery/reprocessing methods.
- Adding new performance reporting functions for IMX and GPX tests (including functions for angle wrapping/unwrapping and time formatting) and updating report file naming.
- Updating references to RTK constants across multiple modules and modifying the LogInspector UI to include new test options.
> SN-6422 gpx rtk unit tests

- src/protocol_nmea.cpp
POWxxx TOW is supossed to be in uS not mS
> SN-6498: POWxx ms to us

- python/logInspector/logInspector.py
- python/logInspector/logInspectorInternal.py
- python/logInspector/logPlotter.py
- python/logInspector/logReader.py
- python/supernpp/supernpp.py
Add root path history selection to Log Inspector for faster access previously used directories.
> Log inspector path history

- src/protocol_nmea.cpp
allows POWxxx to run on windows
> Sn-6499: Add $POWxx Widows support

- python/logInspector/logInspector.py
- python/logInspector/logPlotter.py
- python/logInspector/logReader.py
Add RTK delta time to Log Inspector.
> Log inspector rtk delta time

- scripts/build_manager.py
Cleans cmake caches and both debug and release when clean all is called.
> SN-5079: Adds additional clean functionality to clean_all

- src/ISDisplay.cpp
- src/data_sets.h
SN-6755: Spoof and Jamming Possible no longer alerts user.
> SN-6755: Spoof and Jamming Possible no longer alerts user.

- src/core/base_port.h
read not very readable or troubleshootable.
> SN-6834: baseport.h readability

- ExampleProjects/Simple_Discovery/CMakeLists.txt
- ExampleProjects/Simple_Discovery/Example-2_Device-Discovery.cpp
- src/PortManager.cpp
Example SDK application which demonstrates how to use the new PortManager/DeviceManager to locate a device and communicate with it.
> SN-6692 Simplified Discovery SDK Example

- src/ISDevice.h
- src/InertialSense.cpp
- src/InertialSense.h
- Add description for IMX/GPX flash config sync mechanism.
- Clarify when flash config checksum is invalid.
> Added comment for how flash config sync works

- src/InertialSense.cpp
- src/InertialSense.h
Refactor to simplify these yaml functions using cISDataMappings::DataToYaml.
> Clean up yaml creation using cISDataMappings::DataToYaml

- src/ISConstants.h
> SDK sqr macro

- src/ISBFirmwareUpdater.cpp
- src/ISFirmwareUpdater.h
- src/PortFactory.cpp
Small PR just adds some additional logging (and controls to filter that logging) to the Firmware Updater.  These are primarily internal changes.
> SN-7017 fwUpdate log levels

- src/data_sets.h
> comments on indexing and memory arrangement of covariance

- src/ISConstants.h
- src/ISMatrix.h
Define INS operation limits use for GNSS input.
> SN-6895 gnss input sanity check

- src/DeviceManager.h
- src/ISBFirmwareUpdater.cpp
- src/ISBootloaderISB.cpp
- src/ISBootloaderISB.h
- src/ISComm.h
- src/ISDevice.cpp
- src/ISDevice.h
- src/ISmDnsPortFactory.cpp
- src/InertialSense.cpp
- src/core/tcpPort.c
- src/protocol/mdns.cpp
- src/protocol/mdns.hpp
- src/util/util.cpp
This is a couple of performance improvements around port/device discovery, etc.
Also some changes to allow improved support/performance when upgrading multiple IMX devices using the V2 fwUpdate mechanisms.
Also fixes some stability issues with mDNS discovery.
> SN-6797 Misc Performance Improvements

- cltool/src/cltool.h
- src/ISBootloaderThread.h
- src/ISDataMappings.h
- src/ISDisplay.h
- src/data_sets.h
- src/protocol/mdns.h
SN-7101: IMX-6 Update Hardware Files and Config files to match IMX-6 hardware
> SN-7101: IMX-6 Update Hardware Files and Config files
